import Foundation

func runPresentationTests() {
    precondition(RatioState.make(computer: 4 * 3600, daylight: 2 * 3600) == .share(2.0 / 3))
    precondition(RatioState.make(computer: 0, daylight: 3600) == .share(0))
    precondition(RatioState.make(computer: 3600, daylight: 0) == .share(1))
    precondition(RatioState.make(computer: 0, daylight: 0) == .empty)
    precondition(RatioState.make(computer: 0, daylight: nil) == .unknown)
    precondition(RatioState.make(computer: -.infinity, daylight: 0) == .unknown)
    precondition(RatioState.make(computer: .greatestFiniteMagnitude, daylight: .greatestFiniteMagnitude) == .unknown)
    precondition(OutsideFormat.duration(59) == "0m")
    precondition(OutsideFormat.duration(0.1, remaining: true) == "1m")
    precondition(OutsideFormat.duration(0, remaining: true) == "0m")
    precondition(OutsideFormat.duration(4 * 3600 + 12 * 60 + 59) == "4h12")
    precondition(OutsideFormat.duration(59 * 60 + 1, remaining: true) == "1h00")
    precondition(OutsideFormat.duration(.nan) == "—")
    precondition(OutsideFormat.duration(.greatestFiniteMagnitude) == "168h00")
    precondition(OutsideFormat.clock(59.9) == "59s")
    precondition(OutsideFormat.clock(59.9, remaining: true) == "1m")
    precondition(OutsideFormat.clock(3599.9, remaining: true) == "1h")
    precondition(OutsideFormat.clock(0.1, remaining: true) == "1s")
    precondition(OutsideFormat.clock(0, remaining: true) == "0s")
    precondition(OutsideFormat.clock(-1) == "0s")
    precondition(OutsideFormat.clock(4 * 3600 + 12 * 60 + 59) == "4h 12m 59s")
    precondition(OutsideFormat.clock(3600 + 12) == "1h 12s")
    precondition(OutsideFormat.clock(34 * 60 + 12) == "34m 12s")
    precondition(OutsideFormat.clock(3600 + 34 * 60 + 12) == "1h 34m 12s")
    precondition(OutsideFormat.accessibleDuration(3600 + 12) == "1 hour 12 seconds")
    precondition(OutsideFormat.accessibleDuration(0) == "0 seconds")
    precondition(OutsideFormat.clock(.nan) == "—")
    precondition(OutsideFormat.clock(.infinity) == "—")
    precondition(OutsideFormat.clock(.greatestFiniteMagnitude) == "168h")
    precondition(OutsideFormat.accessibleDuration(3660) == "1 hour 1 minute")
    precondition(OutsideFormat.accessibleDuration(0.1, remaining: true) == "1 second")
    print("PASS: ratio shares, safe compact durations, second clocks, rollovers and spoken precision")
}
